name: Pull Request on Branch Push
on:
  push:
    branches:
    - "*Development"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@devBuild
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                     # If blank, default: triggered branch
        destination_branch: "devBuild"                        # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into devBuild"
        pr_body: ":crown: *An automated PR*"                  # Full markdown support, requires pr_title to be set
        pr_reviewer: "trathod7,ThinkP-Arup"                   # Comma-separated list (no spaces)
        pr_assignee: "trathod7,ThinkP-Arup"                   # Comma-separated list (no spaces)
        pr_label: "auto-pr"                                   # Comma-separated list (no spaces)
        pr_milestone: "Milestone 1"                           # Milestone name
        github_token: ${{ secrets.GITHUB_TOKEN }}
